[project]
name = "card-game"
version = "0.1.0"
description = "Card game for enterteinment purposes"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pygame>=2.6.1",
    "pygwidgets>=1.1.2",
]
